Welp

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,25 +1,32 @@
 #!/bin/bash
 
-# Check if the PYFILE environment variable is set
+# Check if PYFILE environment variable is set
 if [ -z "$PYFILE" ]; then
-    echo "Error: PYFILE environment variable not set."
-    exit 1
+  echo "Error: PYFILE environment variable is not set."
+  exit 1
 fi
 
-# Extract the filename and extension
-filename=$(basename "$PYFILE")
+# Extract filename and extension
+filename=$(basename -- "$PYFILE")
 extension="${filename##*.}"
-filename="${filename%.*}"
+
+# Check if the file has a .py extension
+if [ "$extension" != "py" ]; then
+  echo "Error: The specified file is not a Python script (doesn't have a .py extension)."
+  exit 1
+fi
 
 # Compile the Python script
-python -m py_compile "$PYFILE"
+output_filename="${filename%.*}.pyc"
+python3 -m py_compile "$PYFILE"
 
 # Check if compilation was successful
 if [ $? -eq 0 ]; then
-    # Rename the compiled file
-    mv "__pycache__/$filename.cpython-*.pyc" "${filename}c.pyc"
-    echo "Compilation successful. Compiled file: ${filename}c.pyc"
+  echo "Compiling $PYFILE ..."
+  mv "__pycache__/$filename" "$output_filename"
+  rm -rf "__pycache__"
+  echo "Compilation successful. Output filename: $output_filename"
 else
-    echo "Compilation failed."
-    exit 1
+  echo "Error: Compilation failed."
+  exit 1
 fi
